// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XMY_VIDEO_FILTER_H
#define XMY_VIDEO_FILTER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmy_video_filter_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XMy_video_filter_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XMy_video_filter;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMy_video_filter_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMy_video_filter_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMy_video_filter_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMy_video_filter_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMy_video_filter_Initialize(XMy_video_filter *InstancePtr, u16 DeviceId);
XMy_video_filter_Config* XMy_video_filter_LookupConfig(u16 DeviceId);
int XMy_video_filter_CfgInitialize(XMy_video_filter *InstancePtr, XMy_video_filter_Config *ConfigPtr);
#else
int XMy_video_filter_Initialize(XMy_video_filter *InstancePtr, const char* InstanceName);
int XMy_video_filter_Release(XMy_video_filter *InstancePtr);
#endif

void XMy_video_filter_Start(XMy_video_filter *InstancePtr);
u32 XMy_video_filter_IsDone(XMy_video_filter *InstancePtr);
u32 XMy_video_filter_IsIdle(XMy_video_filter *InstancePtr);
u32 XMy_video_filter_IsReady(XMy_video_filter *InstancePtr);
void XMy_video_filter_EnableAutoRestart(XMy_video_filter *InstancePtr);
void XMy_video_filter_DisableAutoRestart(XMy_video_filter *InstancePtr);

void XMy_video_filter_Set_width(XMy_video_filter *InstancePtr, u32 Data);
u32 XMy_video_filter_Get_width(XMy_video_filter *InstancePtr);
void XMy_video_filter_Set_height(XMy_video_filter *InstancePtr, u32 Data);
u32 XMy_video_filter_Get_height(XMy_video_filter *InstancePtr);

void XMy_video_filter_InterruptGlobalEnable(XMy_video_filter *InstancePtr);
void XMy_video_filter_InterruptGlobalDisable(XMy_video_filter *InstancePtr);
void XMy_video_filter_InterruptEnable(XMy_video_filter *InstancePtr, u32 Mask);
void XMy_video_filter_InterruptDisable(XMy_video_filter *InstancePtr, u32 Mask);
void XMy_video_filter_InterruptClear(XMy_video_filter *InstancePtr, u32 Mask);
u32 XMy_video_filter_InterruptGetEnabled(XMy_video_filter *InstancePtr);
u32 XMy_video_filter_InterruptGetStatus(XMy_video_filter *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
