// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmy_video_filter.h"

extern XMy_video_filter_Config XMy_video_filter_ConfigTable[];

XMy_video_filter_Config *XMy_video_filter_LookupConfig(u16 DeviceId) {
	XMy_video_filter_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMY_VIDEO_FILTER_NUM_INSTANCES; Index++) {
		if (XMy_video_filter_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMy_video_filter_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMy_video_filter_Initialize(XMy_video_filter *InstancePtr, u16 DeviceId) {
	XMy_video_filter_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMy_video_filter_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMy_video_filter_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

